// export * from './civilised/civ01';
export * from './civilised/civ02';
export * from './civilised/civ03';
export * from './civilised/civ04';
export * from './civilised/civ05';
export * from './civilised/civ06';
// export * from './civilised/civ07';
export * from './civilised/civ08';
// export * from './civilised/civ09';
export * from './civilised/civ10';
export * from './civilised/civ11';
export * from './civilised/civ12';
export * from './civilised/civ13';
export * from './civilised/civ14';
export * from './civilised/civ15';

export * from './fame/fam01';
export * from './fame/fam02';
export * from './fame/fam03';
export * from './fame/fam04';
export * from './fame/fam05';
export * from './fame/fam06';
export * from './fame/fam07';
export * from './fame/fam08';
export * from './fame/fam09';

// export * from './regions/reg01';
export * from './regions/reg02';
export * from './regions/reg03';
export * from './regions/reg04';
export * from './regions/reg05';
export * from './regions/reg06';
export * from './regions/reg07';
export * from './regions/reg08';
export * from './regions/reg09';
export * from './regions/reg10';
export * from './regions/reg11';
export * from './regions/reg12';
export * from './regions/reg13';
export * from './regions/reg14';

export * from './tributaries/tri01';
export * from './tributaries/tri02';
export * from './tributaries/tri03';
export * from './tributaries/tri04';
export * from './tributaries/tri05';
// export * from './tributaries/tri06';
export * from './tributaries/tri07';
export * from './tributaries/tri08';
export * from './tributaries/tri09';
// export * from './tributaries/tri10';
export * from './tributaries/tri11';

// export * from './uncivilised/unc01';
export * from './uncivilised/unc02';
export * from './uncivilised/unc03';
export * from './uncivilised/unc04';
export * from './uncivilised/unc05';
export * from './uncivilised/unc06';
export * from './uncivilised/unc07';
export * from './uncivilised/unc08';
export * from './uncivilised/unc09';
export * from './uncivilised/unc10';
export * from './uncivilised/unc11';
export * from './uncivilised/unc12';
// export * from './uncivilised/unc13';
// export * from './uncivilised/unc14';
export * from './uncivilised/unc15';
export * from './uncivilised/unc16';
export * from './uncivilised/unc17';
export * from './uncivilised/unc18';
export * from './uncivilised/unc19';
export * from './uncivilised/unc20';
export * from './uncivilised/unc21';